export const ASSIGNABLE_MACHINERY_NAMES = [
  '8740 S',
  '8740 MF',
  '8741 MF',
  '7719 MF',
  '7719 MF (Black)',
  '7S.180',
  'CAT',
  'CAT Loader',
  'CLAAS JAG',
  'CLAAS XERION',
  'HORSCH 8300',
  'HORSCH PT280',
  'HOLMER T7',
  'JCB 536-95',
  'JCB - Produce Connection',
  'JCB - Pretoria Mepal 2',
  'JCB - Pretoria Mepal',
  'JCB - Pretoria Arable',
  'JCB - Genesis Bio',
  'Maize Maus',
  'Beet Maus',
  'Volvo Shovel',
  'Nurse Slurry Tank',
  'DIGER 1',
  'DIGER 2',
  'PLOEGER MUCK 1',
  'PLOEGER MUCK 2',
  'MANITOU',
];
